Greeting.create!(id: 1, text: "Hello")
Greeting.create!(id: 2, text: "Hey")
Greeting.create!(id: 3, text: "Hi")
Greeting.create!(id: 4, text: "Good Morning")
Greeting.create!(id: 5, text: "Good afternoon")
Greeting.create!(id: 6, text: "Good evening")
Greeting.create!(id: 7, text: "Bonjour")
Greeting.create!(id: 8, text: "Bonsoir")
Greeting.create!(id: 9, text: "What's up?")
Greeting.create!(id: 10, text: "How are you?")